name: special-hooks integration

on:
  pull_request:
    branches: [ master ]
    
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: 16
      - run: node ci
      - run: npm run test
      - run: npm run build
      
